import java.util.Scanner;
import java.util.Random;

public class GuessingGame {
    public GuessingGame() {
        // Scanner to store user input
        Scanner input = new Scanner(System.in);

        boolean correctGuess = false;
        int guess = 0;
        int increment = 0;

        System.out.println("Hello user. What is your name?");
        String name = input.nextLine();

        System.out.println("Welcome, " + name + "! I'm thinking of a number between 1 and 100.");
        Random rand = new Random();


        // Chooses the next number generated by rand from the limit of 1 to 100
        int number = rand.nextInt(100);


        System.out.println("Try to guess my number.");


        while (correctGuess == false) {
            // increase increment value by 1 (when user is guessing incorrectly)
            increment++;

            try {
                guess = input.nextInt();
            }
            catch (Exception e) {
                String badInput = input.next();

                System.out.println("That's not an integer, try again.");

                // skip back to beginning of the while loop
                continue;
            }

            // Check if guess is greater or less than 100
            if (guess > 100 || guess < 1) {
                System.out.println("Your guess is out of range. Please try again.");
            }
            else if (guess > number) {
                System.out.println("Your guess is too high. Please try again.");
            }
            else if (guess < number) {
                System.out.println("Your guess is too low. Please try again.");
            }
            else if (guess == number) {
                System.out.println("Well done, " + name + "! You found my number in " + increment + " tries!");

                // Set correctGuess equal to true since user guessed correctly
                correctGuess = true;
            }
        }
    }
}